# Generated by Django 3.2.5 on 2021-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20210802_1345'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_vote'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='unique_poll_vote'),
        ),
    ]
