# Generated by Django 3.2.5 on 2021-08-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_creatoruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publishedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
