# Generated by Django 3.2.5 on 2021-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210803_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='archivedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
