# Generated by Django 3.2.5 on 2021-08-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='unique_user_rating'),
        ),
    ]
