# Generated by Django 3.2.5 on 2021-08-03 01:45

from django.db import migrations
import extended_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='extendeduser',
            managers=[
                ('objects', extended_user.models.ExtendedUserManager()),
            ],
        ),
    ]
