# Generated by Django 3.2.5 on 2021-07-30 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('archivedAt', models.DateTimeField(default=None)),
                ('publishedAt', models.DateTimeField(default=None)),
                ('editedAt', models.DateTimeField(default=None)),
                ('creatorUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ratings', models.ManyToManyField(related_name='user_rating', through='rating.Rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
