# Generated by Django 3.2.5 on 2021-07-30 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0001_initial'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='votes',
            field=models.ManyToManyField(related_name='user_votes', through='vote.ThreadVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
