# Generated by Django 3.2.5 on 2021-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_thread_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='archivedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='editedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='publishedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
