# Generated by Django 3.2.5 on 2021-08-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='archivedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='editedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='publishedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
