# Generated by Django 3.2.5 on 2021-08-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210803_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='tags',
            field=models.TextField(default='{}'),
        ),
    ]
