# Generated by Django 3.2.5 on 2021-08-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='tags',
            field=models.TextField(default='[]'),
        ),
    ]
