# Generated by Django 3.2.5 on 2021-08-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_poll_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='closedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
