# Generated by Django 3.2.5 on 2021-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publishedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
